### ISSUE TITLE
[Backend Migration 21b] Remove Drizzle, Neon and Clerk

### ISSUE THREAD

**Issue by GonzaloSecades** [GonzaloSecades/nuchi#85]
Second half of #27. Target end state for the programme: **Next + Go, nothing else.** This ticket removes everything non-Go left on the data and auth side.

## Depends on two tickets

- **#84** — the Hono routes are the last consumers of the Drizzle schema and Clerk auth.
- **#89** — nine form/sheet components still import `InsertAccountSchema` / `InsertCategorySchema` / `InsertTransactionSchema` from `db/schema.ts`. `db/` cannot be deleted until those move to contract-derived types.

Starting before both have merged means deleting code that is still imported.

## Scope

**Drizzle / Neon**
- Delete `db/**` (`schema.ts`, `drizzle.ts`, `connection.ts`, `connection.test.ts`).
- Delete `drizzle/**` — the generated SQL migrations. `backend/migrations` (goose) is authoritative now.
- Delete `scripts/migrate.ts` and `scripts/seed.ts`.
- Update `scripts/dev-local.ts`, which invokes the migrate script at line 93.
- Remove `drizzle-orm`, `drizzle-zod`, `drizzle-kit` and the `db:generate` / `db:migrate` / `db:studio` / `db:seed` scripts from `package.json`.

**Clerk**
- Remove `@clerk/nextjs` and `@clerk/backend` from `package.json` (`@hono/clerk-auth` goes with #84).
- Remove the Clerk env vars from `.github/workflows/ci.yml` — the comment there says "the Clerk dependency disappears with #51/#27". This is that moment.
- Remove the whole Clerk block from `.env.example`: `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY`, `CLERK_SECRET_KEY`, `CLERK_PUBLISHABLE_KEY`, `NEXT_PUBLIC_CLERK_SIGN_IN_URL`, `NEXT_PUBLIC_CLERK_SIGN_UP_URL`, and both `..._FALLBACK_REDIRECT_URL` entries.
- Review `ALLOW_DB_SEED` in `.env.example`; it exists only for the seed script this ticket deletes.

## Do NOT remove `pg`

`tests/parity/support/stacks.ts` still imports it. `pg` is removed in #90, which retires that harness. Check every package by usage rather than by name — `db/connection.ts` is not its only consumer.

## Acceptance

- `bun run lint`, `bun test`, `bunx tsc --noEmit`, `bun run build` all clean.
- `bun install` produces no Clerk or Drizzle packages.
- Nothing outside `backend/` talks to Postgres except the parity harness (until #90).
- `bun run build` no longer needs Clerk placeholder keys.
- Closing this, together with #84, closes #27.

**Comment by GonzaloSecades** [comment]
Merged in #99 (`50e874b`). Graphify refreshed on master as `5303105`.

## Verification on the merged head

| check | result |
| --- | --- |
| `bun run lint` | 0 problems |
| `bunx tsc --noEmit` | clean |
| `bun test` | 193 pass, 8 skip, 0 fail — 201 across 20 files |
| `bun run build` | **passes with no Clerk keys in the environment at all** |

The 8 skips are `tests/parity/**`, retired in #90. The test delta from #84 is
exactly `db/connection.test.ts` — 5 tests, 1 file.

One caveat worth recording: the first local typecheck after merging failed with
`Cannot find module '../../app/api/[[...route]]/route.js'` from
`.next/types/validator.ts`. That is a **stale local build artifact** left over
from before #84, not a defect — `rm -rf .next` and it is clean, and CI checks
out fresh so it never saw it.

## Acceptance

- `bun install` produces no Clerk or Drizzle packages — verified against a
  **wiped** `node_modules`, because `bun remove` leaves stale `@clerk/*`
  directories that can mask a surviving import.
- Nothing outside `backend/` talks to Postgres except the parity harness.
- `bun run build` no longer needs Clerk placeholder keys.

## Beyond the ticket text

Three dead things the ticket did not list, each found by checking usage rather
than names: **`drizzle.config.ts`** (importing the removed `drizzle-kit` and
pointing at deleted paths), the **`dev:neon`** script, and **`dotenv`**,
orphaned by this PR's own deletions.

**`bun dev` would have broken silently.** `scripts/dev-local.ts` invoked the
deleted `scripts/migrate.ts`, and no automated check runs the dev script — lint,
typecheck, tests and build all pass with it broken.

Fixing it retired **`docker-compose.dev.yml`**, whose only consumer it was. That
file ran a separate `nuchi_dev` database on port 54329 whose bootstrap superuser
*was* the application role — the layout `docker-compose.yml` documents as unsafe,
since superusers bypass row level security outright.

## `.env.example` now meets this issue's parent criteria

#27 requires it to document the JWT settings; `AUTH_JWT_SECRET` and
`AUTH_COOKIE_SECURE` were missing, so that criterion was unmet on master.

## Review rounds

Three rounds, five findings, all correct and all fixed:

1. Fresh local setup could not bootstrap — no migration step in the canonical
   flow, and the API `os.Exit(1)`s via `VerifyRLSActive` against an unmigrated
   database.
2. `AGENTS.md` still told agents to configure Clerk keys.
3. The migration step I added was not self-contained — nothing exports
   `$DATABASE_URL`. Reproduced the exact failure (`user=zecan database=`) and
   verified the corrected command against live Postgres.
4. My `AGENTS.md` replacement was itself wrong: `NEXT_PUBLIC_API_URL` *is* read
   by Next, in `lib/api-base-url.ts`.
5. `scripts/dev-local.ts` still showed the broken `"$DATABASE_URL"` form after
   the README was fixed.

Copilot did not review this PR — quota limit on all attempts, not a clean pass.

## Follow-ups noticed, not changed

`backend/README.md` has the identical broken `goose ... "$DATABASE_URL"` command
at line 327, and its migrations table lists `00001`-`00003` while `goose status`
reports five. `backend/**` was outside this ticket's scope.

`@paralleldrive/cuid2` is unused by any JavaScript since #84 (the Go side has
its own implementation). Natural to fold into #90 alongside `pg`.

Next and last: #90.
